# -*- coding: utf-8 -*-
"""Добро пожаловать в Colaboratory!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Новый раздел
"""

import matplotlib.pyplot as plt
import numpy as np

# Har bir chiziq uchun koordinatalarni belgilash
x1 = np.array([0, 1, 2, 3])
y1 = np.array([3, 8, 1, 10])

x2 = np.array([0, 1, 2, 3])
y2 = np.array([6, 2, 7, 11])

x3 = np.array([0, 1, 2, 3])
y3 = np.array([5, 9, 2, 8])

x4 = np.array([0, 1, 2, 3])
y4 = np.array([7, 3, 6, 9])

# Grafikni chizish va har bir chiziqqa rang berish
plt.plot(x1, y1, 'o:r', ms=30)
plt.plot(x2, y2, '*-g', ms=10)
plt.plot(x3, y3, '.--y', ms=5)
plt.plot(x4, y4, '+-.b', ms=25)

# Grafik elementlarini sozlash
plt.title("4 Rangli 4 Chiziqli Grafik")
plt.xlabel("X o'qi")
plt.ylabel("Y o'qi")
plt.legend()  # Legenda qo'shish
plt.grid(True)  # Panjara qo'shish

# Grafikni ko'rsatish
plt.show()

import matplotlib.pyplot as pn
import numpy as  np

x = np.array(['ORTIQMIRZO','BEGZOT','BOBURJON','MAVLUDA'])
y = np.array([200,25,500,60])
pn.bar(x,y)
pn.show()

import matplotlib.pyplot as pn
import numpy as  np

x = np.array(['ORTIQMIRZO','BEGZOT','BOBURJON','MAVLUDA'])
y = np.array([200,25,500,60])
pn.barh(x,y)
pn.show()

import matplotlib.pyplot as pn
import numpy as  np

x = np.array(['ORTIQMIRZO','BEGZOT','BOBURJON','MAVLUDA'])
y = np.array([200,25,500,60])
pn.bar(x,y,width=0.1)
pn.show()

import matplotlib.pyplot as pn
import numpy as  np

x = np.array([15,35,10,40])

pn.pie(x)
pn.show()

import matplotlib.pyplot as pn
import numpy as  np

x = np.array([15,35,10,40])
mylabels = ["samsung","redmi","google","apple"]
pn.pie(y,labels=mylabels)
pn.show()

import matplotlib.pyplot as pn
import numpy as  np

x = np.array([15,35,10,40])
mylabels = ["samsung","redmi","google","apple"]
pn.pie(y,labels=mylabels)
pn.show()

import matplotlib.pyplot as pn
import numpy as  np

x = np.array([3,0,0,3,6,6,3])
y = np.array([0,200,500,700,500,200,0])

pn.plot(x,y)
pn.show()

import numpy as np
import IPython.display as display
from matplotlib import pyplot as plt
import io
import base64

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

fig = plt.figure(figsize=(4, 3), facecolor='w')
plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 195), facecolor='g', alpha=0.6)
plt.title("Sample Visualization", fontsize=10)

data = io.BytesIO()
plt.savefig(data)
image = F"data:image/png;base64,{base64.b64encode(data.getvalue()).decode()}"
alt = "Sample Visualization"
display.display(display.Markdown(F"""![{alt}]({image})"""))
plt.close(fig)